### ISSUE TITLE
syncdb -- use os.pathsep instead of linux path separator

### ISSUE THREAD

**Issue by xujianin1988** [zimventures/cpdk#28]
Change the linux path separator to os.pathsep in settings.py.

**Comment by zimventures** [comment]
Rather than using os.path.sep, check out the os.path.normpath function. It'll convert the path to use local path separators and do some other cleanup as well.

**Comment by xujianin1988** [comment]
Fixed committed. Use os.path.normpath to convert the path separators.

**Comment by zimventures** [comment]
You've committed it in your local repository. Now it's time for you to issue a pull request to merge it up into the mainline. Note: don't actually do the merge - I'll handle that :)
