### ISSUE TITLE
CLI: Restrict add/delete for Many-To-Many relationships

### ISSUE THREAD

**Issue by zimventures** [zimventures/cpdk#42]
Currently, a many-to-many relationship allows configuration of the relationship from either side. It may be desirable to only allow configuration from one side:

Given an example of an Employee and Department in a many-to-many relationship. An Employee can be in multiple Departments and a Department can have multiple Employees. However, on the CLI we only want employees to be added and removed from departments. 

```
Global> department sales
department-sales>add employee Frank
department-sales> exit
Global> employee Frank
employee-Frank>add department sales
*** Invalid relationship "department"
employee-Frank>
```

Also automatically handle allowing deletes on the authoritative side of the relationship

```
Global> department sales
department-sales>add employee Frank
department-sales> exit
Global> employee Frank
employee-Frank>exit
Global> delete employee Frank
*** Frank is in use by sales
Global> delete department sales
Global>
```

**Comment by xujianin1988** [comment]
I will take this one as well since this is related to issue #10
