### ISSUE TITLE
CLI: Add SSH support to RedShell

### ISSUE THREAD

**Issue by zimventures** [zimventures/cpdk#5]
Instead of running the CLI as a local process - have it listen on an SSH port (configurable).  
User authenticate will use local account credentials for this version. 
Verify that multiple sessions are supported.

**Comment by zimventures** [comment]
Use Paramiko and simply invoke RedShell. 
https://github.com/paramiko/paramiko/blob/master/demos/demo_server.py

**Comment by xujianin1988** [comment]
Do we need to support windows for this feature ? It's a little bit tricky to configure the windows ssh server using Paramiko.

**Comment by xujianin1988** [comment]
Never mind. Got it work on windows.

**Comment by xujianin1988** [comment]
After some experiments, this issue could be resolved using both Linux and Windows. The subprocess will work on windows with a new sub-thread created and this thread is dedicated to read the output (I read every byte, so we won't have any delay from the redshell process). Currently the only issue I have is the key mapping for <backspace>, <forward>, <backward>, and <delete>, which are commonly used by users. When I typed these keys, the client will send a hex value to the server and if I echo these values back to the client, it won't do the action. I will need to find out the right value sent to client that client could perform the right action. I tried to convert it to utf-8 and ascii and with no luck.

**Comment by zimventures** [comment]
@xujianin1988 - Another thing to consider with regards to the child thread is some type of throttling. Beware of the while(1) loop :)

**Comment by xujianin1988** [comment]
Yeah if the user hits "exit", the thread could close gracefully. Another two scenarios will be user closes the terminal windows and ssh session timeout. I will investigate on these two scenarios, hopefully we could try-except those and send an "exit" to the redshell. We don't want to leave multiple redshell processes running in the background.

**Comment by xujianin1988** [comment]
One question about the unit test, I got the following error when I run the test_redshell:

jixu@ubuntu:~/cpdk$ python -m unittest tests.redshell.test_redshell
Welcome To RedShell!
Global>server s
server s
server-s>ETraceback (most recent call last):
  File "CPDKd.py", line 365, in <module>
    main()
  File "CPDKd.py", line 332, in main
    zmq_cli_socket = setup_cli_zmq(port=settings.ZMQ_SHELL_PORT)
  File "CPDKd.py", line 85, in setup_cli_zmq
    zmq_socket.bind(zmq_listen_addr)
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5653)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:10014)
zmq.error.ZMQError: Address already in use

It looks like the zmq address has already been used, but I don't have any other process that running cpdk staff. Any help would be appreciated !

Thanks,
Jian

**Comment by zimventures** [comment]
Hey Jian,
   Try doing a ps -aux outside of pycharm to see if something is still
running.

~Rob

**Comment by xujianin1988** [comment]
Yeah I tried that, but nothing is running related zmq. I will dive into that, I did a little search online and somebody said its because the zeromq version didn't match with pyzmq version. I'm not sure if it's because that.

**Comment by zimventures** [comment]
Work completed with Pull Request #88. Way to go, @xujianin1988!
